import socket
s=socket.socket()
host=socket.gethostname()
port = 8081
s.bind((host,port))
s.listen(1)
print(host)
print("waiting for incoming connections...")
conn,addr =s.accept()
print(addr, "Has been connected to te server")
filename=input(str("pls enter file to transfer"))
file=open(filename,'rb')
file_data=file.read(1024)
conn.send(file_data)
print("data has been sent")
